// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace DataAnalyzerML.Model
{
    public class ModelInput
    {
        [ColumnName("Count"), LoadColumn(0)]
        public float Count { get; set; }


        [ColumnName("Risk"), LoadColumn(1)]
        public bool Risk { get; set; }


        [ColumnName("URL"), LoadColumn(2)]
        public string URL { get; set; }


        [ColumnName("RiskLevel"), LoadColumn(3)]
        public float RiskLevel { get; set; }


        [ColumnName("LocalPath"), LoadColumn(4)]
        public string LocalPath { get; set; }


    }
}
